### ISSUE TITLE
FoyerError: Found no types for atom 0 (0)

### ISSUE THREAD

**Issue by oakif** [mosdef-hub/foyer#342]
I'm trying to apply a ff to a system that I'm building in mbuild with generic atom type. This means that the pdb files I'm loading the constituent molecules from have identities such as `Z1` and `Z2`. This has worked fine, and hoomd is able to see these atom types after I save the system as a gsd. However, when I try to apply the force field and my system contains these custom atoms, I get the following error:

```
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py:457: UserWarning: Non-atomistic element type detected. Creating custom element for Z1
  'Creating custom element for {}'.format(element))
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py:457: UserWarning: Non-atomistic element type detected. Creating custom element for Z2
  'Creating custom element for {}'.format(element))
Traceback (most recent call last):
  File "my_file.py", line xxx in <module>
    oplsaa = Forcefield(forcefield_files='my_ff.xml')
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 386, in __init__
    Validator(ff_file_name, debug)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/validator.py", line 33, in __init__
    self.smarts_parser = Forcefield(preprocessed_ff_file_name, validation=False).parser
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 400, in __init__
    self.parser = smarts.SMARTS(self.non_element_types)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/smarts.py", line 67, in __init__
    raise FoyerError('Non-element types must start with an underscore, you passed {}'.format(', '.join(optional_names)))
foyer.exceptions.FoyerError: Non-element types must start with an underscore, you passed Z1, Z2
```

From what I'm seeing, mbuild seems to work file with "non-atomistic elements", but foyer has an issue with it. No biggie, I can just prepend the custom elements with an underscore to be `_Z1` and `_Z2`.  However, when I try to apply my custom force field again (with the element names updated), I run into the following error:

```
  File "my_file.py", line xxx, in <module>
    system = oplsaa.apply(system)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 557, in apply
    typemap = self.run_atomtyping(structure, use_residue_map=use_residue_map, **kwargs)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 595, in run_atomtyping
    typemap = find_atomtypes(tmp_res, forcefield=self)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/atomtyper.py", line 65, in find_atomtypes
    _resolve_atomtypes(structure, typemap)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/atomtyper.py", line 136, in _resolve_atomtypes
    atom_id, atoms[atom_id].atomic_number))
foyer.exceptions.FoyerError: Found no types for atom 0 (0).
```

Note that this is only an issue when I'm using `_Z1` and `_Z2`. When I have `H` and `O` (e.g. with water) only in my system, it works fine and applies the force field. 

So, how can I get foyer to apply the force field with my custom system? From what I'm understanding, foyer is saying that atom 0 has no "real" atom type, but of course—it should have type `_Z1`. 

If it helps, here is a snippet of my force field:

```
<ForceField name="My FF" version="1">
  <AtomTypes>
    <Type name="_Z1" class="_Z1" element="_Z1" mass="1"/>
    <Type name="_Z2" class="_Z2" element="_Z2" mass="1"/>
  </AtomTypes>
  <HarmonicBondForce>
    <Bond class1="_Z1" class2="_Z2" length="1" k="50"/>
  </HarmonicBondForce>
</ForceField>
```

**Comment by justinGilmer** [comment]
Hey @oakif ! I think all you are missing are the `smarts` definitions in the force field.

From your FF snippet above:
```xml

<ForceField name="My FF" version="1">
  <AtomTypes>
    <Type name="Z1" class="Z1" element="Z1" mass="1" def=“_Z1”/>
    <Type name="Z2" class="Z2" element="Z2" mass="1" def=“_Z2”/>
...
```


Specially the `def=` section, which is an attribute we added that provides [SMARTS based atom-typing](https://foyer.mosdef.org/en/stable/smarts.html)

Hopefully this helps!

**Comment by oakif** [comment]
@justinGilmer Awesome, thanks a lot for the quick reply! That seems to have solved the issue. I probably should have perused the docs for that one. However, I'm faced with a different issue right after solving this one; maybe you'd be able to help with that as well? 

In this scenario, I have a structure `Z5—Z6—Z7` from mbuild. My force field is as follows:

```
<ForceField name="My FF" version="1">
  <AtomTypes>
    <Type name="_Z5" class="Z5" element="_Z5" mass="1" def="_Z5"/>
    <Type name="_Z6" class="Z6" element="_Z6" mass="1" def="_Z6"/>
    <Type name="_Z7" class="Z7" element="_Z7" mass="1" def="_Z7"/>
  </AtomTypes>
  <HarmonicBondForce>
    <Bond class1="_Z5" class2="_Z6" length="1" k="50"/>
    <Bond class1="_Z6" class2="_Z7" length="1" k="50"/>
  </HarmonicBondForce>
  <HarmonicAngleForce>
    <Angle class1="_Z5" class2="_Z6" class3="_Z7" angle="2.4" k="25"/>
  </HarmonicAngleForce>
</ForceField>
```

However, I get this error now:

```
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py:457: UserWarning: Non-atomistic element type detected. Creating custom element for _Z5
  'Creating custom element for {}'.format(element))
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py:457: UserWarning: Non-atomistic element type detected. Creating custom element for _Z6
  'Creating custom element for {}'.format(element))
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py:457: UserWarning: Non-atomistic element type detected. Creating custom element for _Z7
  'Creating custom element for {}'.format(element))
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/mbuild/compound.py:2412: UserWarning: Guessing that "<_Z5 pos=( 0.0000, 0.0000, 0.0000), 0 bonds, id: 47409079765648>" is element: "EP"
  atom, element))
/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/parmed/openmm/topsystem.py:238: OpenMMWarning: Adding what seems to be Urey-Bradley terms before Angles. This is unexpected, but the parameters will all be present in one form or another.
  'all be present in one form or another.', OpenMMWarning)
Traceback (most recent call last):
  File "polymer_builder.py", line 196, in <module>
    system = oplsaa.apply(system)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 565, in apply
    verbose=verbose, *args, **kwargs)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 631, in parametrize_system
    _check_bonds(data, structure, assert_bond_params)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 280, in _check_bonds
    _error_or_warn(assert_bond_params, msg)
  File "/home/oakif/.conda/envs/hoomd-tf/lib/python3.6/site-packages/foyer/forcefield.py", line 265, in _error_or_warn
    raise Exception(msg)
Exception: Parameters have not been assigned to all bonds. Total system bonds: 2, Parametrized bonds: 0
``` 

From [here](https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefield.py#L270), it seems as though the two bonds `Z5—Z6` and `Z6—Z7` don't have a 'type' property. Is there any other way I need to modify my force field to let that happen? I tried looking at [this](https://foyer.mosdef.org/en/stable/parameter_definitions.html) but it seems like the forces syntax is all correct.

**Comment by rsdefever** [comment]
@oakif I believe your `class` in the `AtomTypes` section need to correspond to the `class` in the `HarmonicBondForce` section. Or vice-versa.

**Comment by oakif** [comment]
@rsdefever Thanks, great catch! That was definitely a problem, haha. Now it seems better but I'm still getting an error: `Exception: Parameters have not been assigned to all bonds. Total system bonds: 2, Parametrized bonds: 1`. At least one bond was parametrized. 

I re-checked the file, and it's definitely the case that Z5 and Z6 are bonded, and Z6 and Z7 are bonded. Not quite sure what the issue is now...

**Comment by oakif** [comment]
@rsdefever Sweet, that was a pretty silly oversight on my part. Thanks a ton to you and @justinGilmer for your help! :)
