### ISSUE TITLE
Cannot atom type a single chlorine

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/foyer#401]
**Bug summary**
Trying to apply `oplsaa` forcefield to a single chlorine atom:

**Code to reproduce the behavior**
```py
$ cat chlorine.mol2 
@<TRIPOS>MOLECULE
chlorine
 1 0 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1 CL          0.0000    0.0000    0.0000 Cl      1  UNL1        0.0000
@<TRIPOS>UNITY_ATOM_ATTR
1 1
charge -1
@<TRIPOS>BOND
$ python
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mbuild as mb
>>> import foyer
>>> cl = mb.load("chlorine.mol2")
>>> opls = foyer.forcefields.load_OPLSAA()
/home/umesh/work/mosdef-hub/foyer/foyer/forcefield.py:502: UserWarning: No force field version number found in force field XML file.
  warnings.warn(
/home/umesh/work/mosdef-hub/foyer/foyer/forcefield.py:514: UserWarning: No force field name found in force field XML file.
  warnings.warn(
/home/umesh/work/mosdef-hub/foyer/foyer/validator.py:132: ValidationWarning: You have empty smart definition(s)
  warn("You have empty smart definition(s)", ValidationWarning)
>>> opls.apply(cl)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umesh/work/mosdef-hub/foyer/foyer/forcefield.py", line 627, in apply
    typemap = self.run_atomtyping(structure, use_residue_map=use_residue_map, **kwargs)
  File "/home/umesh/work/mosdef-hub/foyer/foyer/forcefield.py", line 665, in run_atomtyping
    typemap = find_atomtypes(tmp_res, forcefield=self)
  File "/home/umesh/work/mosdef-hub/foyer/foyer/atomtyper.py", line 79, in find_atomtypes
    _resolve_atomtypes(topology_graph, typemap)
  File "/home/umesh/work/mosdef-hub/foyer/foyer/atomtyper.py", line 151, in _resolve_atomtypes
    raise FoyerError("Found no types for atom {} ({}).".format(
foyer.exceptions.FoyerError: Found no types for atom 0 (17).
>>> 

```

**Comment by daico007** [comment]
I just checked the `oplsaa.xml` and I think we don't currently have any atomtype for `Cl` (there is a few atom type of `Cl` but they are all missing SMARTS string).
