### ISSUE TITLE
Error exit upon failure to find atom type

### ISSUE THREAD

**Issue by iGulitch** [mosdef-hub/foyer#589]
**Describe the behavior you would like added to Foyer**

When Foyer can't find an atom type in `*.xml` file for an atom during the FF application to a molecule, it exits immediately with error message and big **python** error traceback :
```
>>> mol_ff = ff.apply(mol)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/foyer/foyer/forcefield.py", line 758, in apply
    typemap = self.run_atomtyping(
              ^^^^^^^^^^^^^^^^^^^^
  File "/foyer/foyer/forcefield.py", line 837, in run_atomtyping
    typemap = find_atomtypes(structure, forcefield=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/foyer/foyer/atomtyper.py", line 146, in find_atomtypes
    _resolve_atomtypes(topology_graph, typemap)
  File "/foyer/foyer/atomtyper.py", line 221, in _resolve_atomtypes
    raise FoyerError(
foyer.exceptions.FoyerError: Found no types for atom numbered 2 which is atomic number 6. Forcefield file is missing this atomtype, so try to add SMARTS definitions to account for this atom.
```
However, there might be other atoms, for which atom types info is missing, which the user won't know about until the current issue is fixed. That would be useful, if all such problems are collected and reported all at once, e.g. :
```
Found no types for atom numbered i1 which is atomic number n1.
Found no types for atom numbered i2 which is atomic number n2.
...
Found no types for atom numbered i3 which is atomic number n3.
```
Also, perhaps, suppressing the **python** output would also be nice?

**Comment by CalCraven** [comment]
Yes, this whole feature I've come to name "The Forcefield Debugging Suite." I have a semi-working version kept locally, the issue is that it has required some hard changes to the common behaviors in GMSO and Foyer that are there for validation checking. So I need to implement a more flexible method of turning it on and off then what I currently use. 

It should (and has some current functionality for)
1. show graphs of molecule with missing typed atoms and bonds
2. Take a huge list of molecules and determine the number of missing atomtypes (and their possible associated SMARTS strings)
3. Help catch bugs in forcefield xmls better than the current xml format does.
4. Allow you to maintain debugged versions of xmls in memory instead of hand writing changes to the xml each time and reloading and running your apply steps.


If you have other suggests for such a tool, let me know, since I agree it's a badly needed feature. Also, apologies for the slow responses to these issues, so much of the development is happening on the GMSO side (this entire feature would have to live in GMSO), that Foyer kind of gets left by the way side since it is so ParmED reliant, and therefore pretty much stable as is.

**Comment by CalCraven** [comment]
It's also suggested by someone that a way to intuitively deal with conflicts in a forcefield file, and remove overlapping parameters would be extremely useful when building new forcefield files.

**Comment by iGulitch** [comment]
Thanks for the reply and the detailed explanation, @CalCraven !
From now on, I'm gonna be bothering you in the GMSO repo, not in Foyer's ;)

**Comment by CalCraven** [comment]
No problem @iGulitch, Looking forwards to it!
